### ISSUE TITLE
Update account when changed in wallet

### ISSUE THREAD

**Issue by mfbz** [rentfuse-labs/neo-wallet-adapter#14]
If the account is changed in the wallet, currently the account property of the adapter is not updated.
The idea is to add a listener for the **ACCOUNT_CHANGED** event in Neoline and O3 to change the account accordingly.

**Comment by alexsteixeira** [comment]
related: https://github.com/rentfuse-labs/neo-wallet-adapter/issues/14

**Comment by mfbz** [comment]
Implemented in #29 🥳
