### ISSUE TITLE
Can't connect with Neon Wallet Mobile using WalletConnect

### ISSUE THREAD

**Issue by EdgeDLT** [rentfuse-labs/neo-wallet-adapter#24]
COZ has just released WalletConnect in Neon Wallet Mobile (iOS/Android). I've tested the integration with a few apps; Flamingo, QuickVote, and GhostMarket work (GM didn't initially but seems to now). Now trying to connect to Neonova, but the connection hangs. Reckon that probably means there's a tweak to be made in this library somewhere.

**Comment by mfbz** [comment]
Hey Thanks Edge!
Yep i think that maybe some updates have to be done on the neo-wallet-adapter library to make this work

**Comment by mfbz** [comment]
Hey @EdgeDLT it should be fixed now, i close this.
If you encounter again the problem post it again 😇
