### ISSUE TITLE
Beta version support to new walletconnect SDK

### ISSUE THREAD

**Issue by mfbz** [rentfuse-labs/neo-wallet-adapter#32]

**Comment by gsmachado** [comment]
What's the "new" walletconnect SDK?

**Comment by mfbz** [comment]
CoZ is updating the fantastic https://github.com/CityOfZion/wallet-connect-sdk library with a newer version that has breaking changes.

When they do so, they will update Neon Wallet to follow this new version, so to keep our compatibility we need to update the walletconnect adapter as well 🤓

**Comment by csmuller** [comment]
The "Migration Event" for this, i.e., deadline is set to Sept 27th (see [here](https://github.com/CityOfZion/wallet-connect-sdk/blob/develop/MIGRATION.md))

**Comment by mfbz** [comment]
Yesss, thank you @csmuller 😊

**Comment by mfbz** [comment]
Version **0.4.0-beta1** supporting the new walletconnect SDK has been published to npm! 🚀

**Comment by mfbz** [comment]
Added with #35
