### ISSUE TITLE
Can we export these tools to an index.js to embeed with Web requirement

### ISSUE THREAD

**Issue by vncoelho** [rentfuse-labs/neo-wallet-adapter#33]
We would like to know the best way to integrate it to an html/js pure website.

**Comment by mfbz** [comment]
Possible duplicate of #31.
It would be needed to create a bundled minified version of the packages needed with Webpack or bundler like that.

**Comment by vncoelho** [comment]
Thanks, that will be a duplicated.
The title is not the same but result will.
